name: bevis
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.6.3+23
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  uri: ^1.0.0
  qr_code_scanner: ^0.5.1
  path_provider: ^2.0.1
  provider: ^5.0.0
  sqflite: ^2.0.0
  event_bus: ^2.0.0
  flutter_slidable: ^0.6.0
  url_launcher: ^6.0.3
  permission_handler: ^7.1.0
  location: ^4.3.0
  geocoding: ^2.0.0

  #NEEDED FOR WEB IMPLEMENTATION
  google_geocoding: ^0.2.0
  
  intl: ^0.17.0
  image_picker: ^0.8.0+3
  package_info_plus: ^1.0.3
  flutter_svg: ^0.22.0
  webview_flutter: ^2.0.8
  flutter_facebook_auth: ^3.4.0
  cached_network_image: ^3.0.0
  #Firebase Plugins
  flutter_screenutil: ^5.0.0+2
  progress_dialog: ^1.2.1
  equatable: ^2.0.3
  path: ^1.8.0

  flutter_repository:
    git:
      url: https://github.com/RostykStakhiv/flutter_repository.git
      ref: 30b025a8b9f33d103ae3817bcf1e5da83aec3322
  flutter_zip_archive:
    git:
      url: https://github.com/RostykStakhiv/flutter_zip_archive.git
      ref: ea4e05999b9ac63ef06bf2dcde90cfee317d5543
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  email_validator: ^2.0.1
  dio: ^4.0.0
  google_sign_in: ^5.0.3
  filesize: ^2.0.1
  crypto: ^3.0.1
  get_ip: ^0.4.0
  device_info: ^2.0.1
  mime_type: ^1.0.0
  rxdart: ^0.27.1
  local_auth: ^1.1.5
  file_picker: ^3.0.2+2
  flutter_spinkit: ^5.0.0
  bot_toast: ^4.0.1
  page_transition: ^2.0.2
  pdf_render: ^1.0.11
  flutter_swiper_null_safety: ^1.0.2
  share_plus: ^2.1.4
  flutter_image_compress: ^1.0.0
  photo_view: ^0.11.1
  toast: ^0.1.5
  flutter_inapp_purchase: ^5.0.1
  loadmore: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/app_icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    #general
    - assets/asset_preview_page/
    - assets/

    #select_file_page
    - assets/select_file_page/

    #tutorial
    - assets/tutorial/

    #login
    - assets/login/

    #Home
    - assets/home/

    #menu
    - assets/menu/

    #bottom sheet
    - assets/bottom_sheet/

    #checkboxes
    - assets/widgets/checkboxes/

    #asset details
    - assets/asset_details/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: segoe
      fonts:
        - asset: assets/fonts/segoeui.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
